server:
  port: 3000 # ${PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thrivex?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root # ${DB_USERNAME}
    password: 123456 # ${DB_PASSWORD}

domain: http://localhost:8080 # ${DOMAIN}
